[workspace]
members = [
    "obsv-core",
    "obsv-collect",
    "obsv-monitor",
    "obsv-api",
    "obsv-notify",
    "obsv-bin",
    "lib/obsv-message",
    "lib/obsv-otlp",
    "lib/obsv-grafana",
]
