[workspace]
resolver = "2"
members = [
    # "libs/obsv-core",
    # "libs/obsv-otlp",
    "libs/obsv-not",
    # 
    # "obsv-core",
    # "obsv-collect",
    # "obsv-monitor",
    # "obsv-api",
    # "obsv-notify",
    # "obsv-bin",
    # "lib/obsv-message",
    # "lib/obsv-grafana",
]
