[package]
name = "obsv-collect"
version = "0.1.0"
edition = "2021"
description = "Data collector"
license = "MIT OR Apache-2.0"
repository = "https://github.com/nlargueze/obsv"

[dependencies]
opentelemetry_sdk = { version = "0.19.0" }
