[env]
RUST_LOG = "info,mio=off,obsv-core=trace,clickhouse-client=trace"
OBSV_OTEL_PROTO_VERSION = "0.19.0"

[alias]
curly = "run --bin curly --"
curly-rel = "run --bin curly --release --"
RUST_LOG = "trace"
