[package]
name = "obsv-api"
version = "0.1.0"
edition = "2021"
description = "Data API server"
license = "MIT OR Apache-2.0"
repository = "https://github.com/nlargueze/obsv"

[dependencies]
hyper = { version = "0.14.26", features = ["full"] }
tokio = { version = "1.28.1", features = ["full"] }
