receivers:
  otlp:
    protocols:
      # TCP listsner on 4317
      grpc:
      # HTTP listsner on 4318
      http:

processors:
  batch:

exporters:
  logging:
    verbosity: detailed
  clickhouse:
    endpoint: tcp://clickhouse:9000
    # endpoint: http://clickhouse:8123 => OK
    database: otel
    ttl_days: 3
    timeout: 5s
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s
    # sampling_initial: 5
    # sampling_thereafter: 200

extensions:
  # Checks if the collector is UP (port 13133)
  health_check:
  # Profiling
  pprof:
  # Debug pages (port 55679)
  zpages:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, clickhouse]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, clickhouse]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, clickhouse]
