[package]
name = "obsv-grafana"
version = "0.1.0"
edition = "2021"
description = "Grafana connector"
license = "MIT OR Apache-2.0"
repository = "https://github.com/nlargueze/obsv"

[dependencies]
serde = { version = "1.0.163", features = ["derive"] }
